version: '3'

networks:
  gfcams-network:
    driver: bridge

services:

        gfcams:
            container_name: gfcams
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - gfcams-network
            ports:
                - "9001:9000"
            volumes:
                - ./../gfcams:/gfcams:rw,cached
                - gfcams_log:/gfcams/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - mariadb-master

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "81:80"
                - "443:443"
            networks:
                - gfcams-network
            depends_on:
                - gfcams
            volumes:
                - ./../gfcams/public:/gfcams/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            networks:
                - gfcams-network

        portainer:
            image: portainer/portainer-ce:latest
            container_name: portainer
            restart: always
            security_opt:
                - no-new-privileges:true
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - /var/run/docker.sock:/var/run/docker.sock:ro
                - ./portainer-data:/data
            ports:
                - 8000:8000
                - 9443:9443
            networks:
                - gfcams-network

        memcached:
            container_name: memcached
            image: memcached:latest
            networks:
                - gfcams-network

        mariadb-master:
            container_name: mariadb-master
            image: mariadb:latest
            env_file:
                - ./db/master/.env.master
            volumes:
                - ./db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/master/maria.master.cnf:/etc/mysql/conf.d/maria.master.cnf
                - ./db/master/.data/mysql:/var/lib/mysql:rw
            ports:
                - "5506:3306"
            networks:
                - gfcams-network

        mariadb-slave-1:
            container_name: mariadb-slave-1
            image: mariadb:latest
            env_file:
                - ./db/slaves/email/.env.slave
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/email/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                - ./db/slaves/email/.data/mysql:/var/lib/mysql:rw
            ports:
                - "5507:3306"
            depends_on:
                - mariadb-master
            networks:
                - gfcams-network

        mariadb-slave-2:
            container_name: mariadb-slave-2
            image: mariadb:latest
            env_file:
                - ./db/slaves/sms/.env.slave
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/sms/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                - ./db/slaves/sms/.data/mysql:/var/lib/mysql:rw
            ports:
                - "5508:3306"
            depends_on:
                - mariadb-master
            networks:
                - gfcams-network

        mariadb-slave-3:
            container_name: mariadb-slave-3
            image: mariadb:latest
            env_file:
                - ./db/slaves/gps/.env.slave
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/gps/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                - ./db/slaves/gps/.data/mysql:/var/lib/mysql:rw
            ports:
                - "5509:3306"
            depends_on:
                - mariadb-master
            networks:
                - gfcams-network

        mariadb-slave-4:
            container_name: mariadb-slave-4
            image: mariadb:latest
            env_file:
                - ./db/slaves/mms/.env.slave
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/mms/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                - ./db/slaves/mms/.data/mysql:/var/lib/mysql:rw
            ports:
                - "5510:3306"
            depends_on:
                - mariadb-master
            networks:
                - gfcams-network

volumes:
    nginx_log:
    gfcams_log:
    db:
        driver: local